version: "3.8"

services:

  mongodb:
    image: mongo
    ports:
    - 27017:27017
    environment:
    - TZ=Europe/Paris

  neo4j:
    image: neo4j
    ports:
    - 7474:7474
    - 7687:7687
    environment:
    - NEO4J_AUTH=neo4j/password
